[[pages]]
path = "homepage.py"
name = "Home"
icon = "🏠"

[[pages]]
path = "pages/contact.py"
name = "Contact"
icon = ":books:"

[[pages]]
path = "pages/thanks.py"
name = "Thanks"
icon = ":wave:"

[[pages]]
path = "pages/projects.py"
name = "Projects"
icon = ":wave:"
is_section = true

[[pages]]
path = "pages/project1.py"
name = "Project 1"
icon = ":bee:"

[[pages]]
path = "pages/project2.py"
name = "Project 2"
icon = ":bee:"

[[pages]]
path = "pages/project3.py"
name = "Project 3"
icon = ":bee:"
is_section = false

