[[pages]]
path = "homepage.py"
name = "Home"
icon = "🏠"

[[pages]]
path = "pages/contact.py"
name = "Contact"
icon = ":books:"

[[pages]]
path = "pages/thanks.py"
name = "Thanks"
icon = ":clap:"

[[pages]]
path = "pages/skills.py"
name = "Skills"
icon = ":hammer:"

[[pages]]
path = "pages/projects.py"
name = "Projects"
icon = ":wave:"

[[pages]]
path = "projects/StreamlitPortfolio/StreamlitPortfolio.py"
name = "Streamlit Portfolio"
icon = ":bee:"

[[pages]]
path = "projects/Multi-agentReinforcementLearning/Multi-agentReinforcementLearning.py"
name = "Multi-agent Reinforcement Learning"
icon = ":bee:"

[[pages]]
path = "projects/ContinuousControlReinforcementLearning/ContinuousControlReinforcementLearning.py"
name = "Continuous Control Reinforcement Learning"
icon = ":bee:"

[[pages]]
path = "projects/DengAI/DengAI.py"
name = "DengAI"
icon = ":bee:"






